export const legalContents = {
  privacy: `
Full Privacy Policy for FileTrackr

**1. Introduction** The **Abra Provincial Health Office (PHO)** is committed to protecting the personal data of its employees and authorized personnel. This Privacy Policy explains how the **FileTrackr Document Tracker** collects, processes, and protects your information in accordance with the **Philippine Data Privacy Act of 2012 (RA 10173)**.

**Effective Date:** August 26, 2026

**2. Who is Responsible for Your Personal Data**

**Organization:** Abra Provincial Health Office

**Address:** Bangued, Abra, Philippines

**Data Protection Officer (DPO):** Antonio L. Valera, M.D.

**System Administration:** System oversight is managed by the ICT Officer Designate, **Justice P. Belleza**. Inquiries regarding system data can be directed to the ICT office.

**3. Personal Information We Collect** As an internal administrative tool, FileTrackr collects **only the data strictly necessary** for system operation:

**Account Information:** Full name, official government email address, department assignment, and designated system role.

**Activity & Audit Logs:** Timestamps of logins, documents routed, actions executed (e.g., received, forwarded), and system usage metrics.

**IP/Device Information:** IP addresses, browser types, and device identifiers collected during active sessions to detect and prevent unauthorized access.

**Cookies & Security Tokens:** Cryptographic tokens generated by security verification widgets.

**4. How and Why We Use Personal Information** We process your personal information for the following purposes:

**Accountability & Tracking:** To maintain a **transparent, verifiable chain of custody** for all official documents.

**Security & Access Control:** To authenticate users, enforce role-based access restrictions via **Row Level Security (RLS)**, and block automated bot attacks.

**5. Disclosure and Sharing of Personal Information** Your data is **strictly confidential** and is only disclosed to the following entities:

**Authorized Personnel:** System administrators, your direct supervisors, and specific colleagues.

**Hosting & Cloud Providers:** Our cloud database provider (Supabase) and network security provider (Cloudflare).

**Government Authorities:** The **Commission on Audit (COA)**, **Civil Service Commission (CSC)**, or other legal authorities, but **only when formally and legally required**.

**6. Data Retention** Personal information and audit logs are retained in accordance with the official records disposition schedules mandated by the **National Archives of the Philippines (NAP)** and local provincial guidelines.

**7. Security Measures** We implement **robust organizational, physical, and technical safeguards**, including strict database Row Level Security (RLS) policies, encrypted data transmissions, and bot protection challenges.

**8. Rights of Data Subjects** Under the Data Privacy Act, you possess rights to be informed, access, correct, object, erase, and file a complaint regarding your personal data. To exercise any of these rights, submit a **written request via official email** to the ICT Officer Designate.
`,

  terms: `
Terms and Conditions of Use for FileTrackr

**Effective Date:** August 26, 2026

These Terms and Conditions govern the access to and use of FileTrackr, an official digital administrative service of the Abra Provincial Health Office. They establish the rules and responsibilities applicable to users of the System and shall be read together with applicable civil service laws, internal administrative issuances, and the System's Privacy Policy.

**1. Purpose and Authority** FileTrackr is an internal electronic document tracking and routing system operated by the Abra Provincial Health Office. Its primary purpose is to establish a **transparent, accountable, and highly verifiable chain of custody** for official agency documents and communications. The operation of this system supports the agency's mandate for efficient public administration, official records management, and operational transparency.

**2. Scope of the Terms** These Terms apply exclusively to authorized internal users, including:

**Employed personnel and officials** of the Abra Provincial Health Office, including the following District, Municipal, and Medicare Hospitals: Abra Provincial Hospital, La Paz District Hospital, Villaviciosa Medicare and Community Hospital, Dolores Medicare and Community Hospital, and Bucay Municipal Hospital.

**System administrators** and designated ICT staff.

**Authorized clerks** and document custodians operating within the system's approved workflows.

**External / Inter-Agency Access:** Use of the System by offices, departments, or agencies outside the Abra Provincial Health Office hospital network is strictly conditional upon the execution and approval of a formal **Memorandum of Agreement (MOA)** and **Data Sharing Agreement (DSA)** with the Abra Provincial Health Office. Public access to the system backend or administrative dashboards is strictly prohibited.

**3. Access and Account Registration**

**Eligibility:** Access is **restricted to active personnel** of the Abra Provincial Health Office and its associated district hospitals. 

**Account Creation:** Accounts are provisioned centrally by the system administrators. Self-registration by unauthorized external parties is disabled.

**Credential Security:** Users are **solely responsible** for maintaining the confidentiality of their passwords and passkeys. 

**Account Deactivation:** Access will be immediately suspended or deactivated upon an employee's separation from the agency, transfer to an ineligible department, or upon administrative order.

**4. Acceptable and Prohibited Use** FileTrackr is **strictly for official government business**. Users are **prohibited** from:

**Bypassing Security:** Attempting to bypass or manipulate **Row Level Security (RLS)** policies to access documents outside their department or clearance level.

**Sharing Credentials:** Using another employee's account or **sharing login credentials**.

**Falsifying Records:** **Falsifying document tracking data**, backdating routing logs, or submitting fraudulent administrative records.

**System Interference:** Introducing malicious software, performing automated scraping, or interfering with system availability.

**Unlawful Use:** Using the platform for personal storage, unauthorized communications, or unlawful activities.

**5. Government Information and Official Records**

**Restricted Information:** All routing logs, tracking metrics, and document metadata within FileTrackr are classified as **internal government records**. They are not for public distribution unless explicitly released through official Freedom of Information (FOI) procedures.

**Official Evidence:** System-generated timestamps and user audit logs are considered **official, legally binding records** of a document's custody and routing history. 

**Reference Numbers:** Users must utilize the system-generated tracking IDs when inquiring about a document's status.

**6. Accuracy of Information** Users are **administratively responsible** for ensuring that the actions they log (e.g., "Received," "Forwarded") **accurately reflect the physical reality** of the document's location. The Abra Provincial Health Office assumes no liability for administrative delays caused by user input errors or failure to update tracking statuses promptly.

**7. Privacy and Personal Information** The system processes personnel data (names, roles, login logs) strictly to maintain administrative accountability. Pursuant to the **Data Privacy Act of 2012 (Republic Act No. 10173)**, the Abra Provincial Health Office operates as the Personal Information Controller (PIC) for administrative personnel accounts and official health records processed within the System. For a comprehensive breakdown of what data is collected, your rights, and contact details for the Data Protection Officer, please refer to the **FileTrackr Privacy Policy**.

**8. System Availability** The Abra Provincial Health Office ICT office will endeavor to ensure continuous system availability during standard government operating hours. However, access may be temporarily suspended due to scheduled maintenance, network interruptions, or emergency security patching.

**9. Security Responsibilities** The agency utilizes advanced security safeguards, including encrypted database connections and bot-mitigation challenges. Users must actively participate in system security by utilizing secure local devices, reporting suspicious account activity immediately, and ensuring they log out of shared terminals.

**10. Intellectual Property** The FileTrackr system architecture, source code, database schemas, and user interface workflows are the proprietary intellectual property of the Abra Provincial Health Office. Users and connected units are granted a revocable, non-exclusive, non-transferable license to access the platform. Decompilation, code extraction, unauthorized reproduction, or unauthorized third-party deployment without prior written authorization from the Provincial Health Officer is strictly prohibited. 

**11. Third-Party Services** FileTrackr relies on enterprise-grade third-party infrastructure to function, including **Supabase / AWS** for secure cloud database hosting and **Cloudflare** for network routing and security verification. These providers process encrypted system data strictly on behalf of the Abra Provincial Health Office.

**12. Electronic Transactions and Logs**

**Electronic Acknowledgment:** Clicking "Receive" or "Forward" within the system constitutes a **formal electronic acknowledgment** of document custody.

**Timestamps:** The exact server time recorded at the moment of submission serves as the **official timestamp** of the transaction for compliance and auditing purposes.

**Digital Signatures & Passkeys:** Captured digital signatures and biometric authentications performed within the system are recognized as legally binding electronic signatures pursuant to the **Electronic Commerce Act of 2000 (Republic Act No. 8792)** and the Rules on Electronic Evidence. 

**13. Suspension and Termination** System access may be administratively suspended or revoked prior to an employee's departure upon detection of unauthorized access attempts, documented violations of these Terms of Use, or pending administrative investigations requiring the preservation of audit logs.

**14. Complaints and Assistance** For technical support, password resets, or to report system errors, users must contact the ICT Officer Designate. Disputes regarding document routing timelines or missing files should be directed to the respective department heads or the PESU Program Coordinator.

**15. Changes to the Terms** The Abra Provincial Health Office reserves the right to amend these Terms. Material changes to system rules will be communicated via administrative memorandum or an in-app notification upon your next login.

**Current Version:** 1.1.8 (August 2026)
`,

  aup: `
Information Security and Acceptable Use Policy for FileTrackr

**Effective Date:** August 26, 2026

**1. Purpose** This Acceptable Use Policy (AUP) outlines the **mandatory security practices** and acceptable use standards for all personnel accessing **FileTrackr**. **Strict adherence** to these rules is required to protect government data from unauthorized access, alteration, or disclosure.

**2. Scope** This policy applies to **all authorized users** across the Abra PHO and its associated facilities (Abra Provincial Hospital, La Paz District Hospital, Villaviciosa Medicare, Dolores Medicare, and Bucay Municipal Hospital).

**3. Account and Credential Security** Your FileTrackr account is tied to your **official digital identity**. You are **strictly responsible** for all actions taken under your account.

**No Sharing:** You must **never share your password, passkey, or biometric authentication device** with anyone, including your direct supervisor or ICT personnel. 

**Session Management:** You must **explicitly log out** of FileTrackr or lock your workstation when stepping away from your desk.

**4. Data Handling and Confidentiality** 

**Need-to-Know Basis:** You may only access, view, or route documents that are relevant to your official duties and department. 

**No Unauthorized Duplication:** Capturing screenshots, taking photographs of your monitor, or exporting routing logs for personal use or unauthorized distribution is **strictly prohibited**.

**Verification of Physical Custody:** When clicking "Receive" or "Forward" in the system, you must ensure you have **physical possession** of the corresponding document. Falsifying the digital location of a document is an **administrative offense**.

**5. Prohibited Activities** Under **no circumstances** shall users engage in the following activities on FileTrackr:

**Privilege Escalation:** Attempting to manipulate the system's Row Level Security (RLS) to gain administrative privileges.

**Impersonation:** Logging in using another employee's credentials to process documents on their behalf.

**System Disruption:** Introducing malware or executing automated scripts (scraping).

**Non-Official Use:** Utilizing the tracking system to process **personal documents or unofficial business**.

**6. Incident Reporting** You must **immediately report** to the ICT Officer Designate any suspicion that your password has been compromised, or if you notice unauthorized routing actions logged under your name.

**7. Policy Enforcement and Disciplinary Action** System activity is actively logged and audited. Violations of this Acceptable Use Policy may result in **immediate suspension** of your FileTrackr account and **administrative disciplinary action** in accordance with Civil Service Commission (CSC) rules.
`
};